### ISSUE TITLE
React Dev Tools doesn't work with Loxe

### ISSUE THREAD

**Issue by christianramsey** [ahomu/Loxe#4]
When running npm start in the repository (after npm install) React dev tools doesn't display and instead this warning appears in Chrome Dev Tools 

```
Download the React DevTools for a better development experience: https://fb.me/react-devtools
```

**Comment by ahomu** [comment]
Is this screen?

<img width="1070" alt="screen shot 2015-07-29 at 00 47 11" src="https://cloud.githubusercontent.com/assets/404356/8936115/701b3966-358b-11e5-96ee-06f5e3fbec1f.png">

**Comment by christianramsey** [comment]
Must have been a kink because it's working for us as well. Cheers.
